### PR TITLE
Update quick_start.md

### PR DESCRIPTION
**Pull request by huzk8**
fix  table format of quickstart doc

Fixes #<xyz>

where *XYZ* should be replaced by the actual issue number.

### Motivation

fix doc.

### Modifications

fix markdown table format error.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by gosonzhang — APPROVED** [review]
+1

**Comment by gosonzhang** [comment]
@huzk8, thanks!

**Comment by dockerzhang** [comment]
@gosonzhang @huzk8 this commit is not correct, it must create an issue firstly and relate to it. Please pay attention next time.

**Comment by huzk8** [comment]
Thx.



发自我的iPhone


------------------ Original ------------------
From: dockerzhang ***@***.***&gt;
Date: Mon,Nov 22,2021 8:30 PM
To: apache/incubator-inlong-website ***@***.***&gt;
Cc: huzk ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-inlong-website] Update quick_start.md (PR #191)






@gosonzhang @huzk8 this commit is not correct, it must create an issue firstly and relate to it. Please pay attention next time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
